In [1]:
import tensorflow as tf
from pathlib import Path

SAMPLE_FILEPATH = Path('../dataset/raw/Ngadas/Marsam.wav')

In [2]:
import os

def get_dialect(file_path):
    parts = tf.strings.split(
        file_path,
        sep=os.path.sep
    )
    return parts[-2]

get_dialect(SAMPLE_FILEPATH.__str__())

2022-02-08 15:57:07.732019: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-08 15:57:07.773249: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-08 15:57:07.773492: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-02-08 15:57:07.774739: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags

<tf.Tensor: shape=(), dtype=string, numpy=b'Ngadas'>

In [3]:
def get_wave(path) -> tf.Tensor:
    """A function to get waveform from a file path.

    Args:
        path ([type]): [description]

    Returns:
        [type]: [description]
    """
    path = tf.io.read_file(path.__str__())
    wav, _ = tf.audio.decode_wav(path)
    return tf.squeeze(wav, axis=-1)

_wav = get_wave(SAMPLE_FILEPATH)
_wav

<tf.Tensor: shape=(152916442,), dtype=float32, numpy=
array([0.        , 0.        , 0.        , ..., 0.00195312, 0.00195312,
       0.00198364], dtype=float32)>

In [ ]:
def get_spectrogram(wav):
    """A function to get spectrogram from a waveform.

    Args:
        wav ([type]): [description]

    Returns:
        [type]: [description]
    """
    spec = tf.abs(tf.signal.stft(wav, frame_length=1024, frame_step=256))
    return tf.squeeze(spec, axis=-1)

## TODO: either continue TF implementation or use librosa.